title: Home page of Anatoly Trosinenko
description: Finding some interesting technologies, testing, extending and blogging about
baseurl: ""
url: "https://atrosinenko.github.io"
github_username: atrosinenko


markdown: kramdown
theme: jekyll-theme-hacker
